### PR TITLE
Fixes #12340 - resend button shows countdown now

### PR DESCRIPTION
**Pull request by lzap**
Replaces https://github.com/theforeman/foreman-discovery-image/pull/43

### CODE REVIEW

**Comment by lzap** [comment]
Now this applies cleanly @stbenjam thanks!

**Comment by lzap** [comment]
This is the very last one and then I can rebase upstream and downstream as well... thank you!

**Comment by lzap** [comment]
Once merged into `master`, can you please push a new tag `3.0.4` there immediately, so jenkins create new nightly build with bumped version already? Thanks.

**Comment by stbenjam** [comment]
Merged as 0febbb02fea80d24b3229be88ae5ad087a193eb2 and tagged as 3.0.4

**Comment by lzap** [comment]
Thanks so much, final release yay!

**Comment by lzap** [comment]
Build is up for the record: http://downloads.theforeman.org/discovery/nightly/

**Pull request closed without merging**
