### PR TITLE
Reintroduce ethtool facts

### PR DESCRIPTION
**Pull request by petski**
ethtool facts were removed in 68f2446aa90c5436e0ca85925fd9b6ea222fdb8e

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thank you so much! I will test and push out a minor release, looks like you need this. Sorry about removing that. BTW what do you need this for? I could not figure out why this is actually there.

**Comment by lzap** [comment]
I only have a virtual host handy, but the code appears to work without any errors:

```
[root@fdi ~]# ethtool eth0
Settings for eth0:
	Link detected: yes
[root@fdi ~]# FACTERLIB=/usr/share/fdi/facts tfm-ruby /opt/theforeman/tfm/root/usr/bin/facter | grep duplex
nmprimary_802-3-ethernet_duplex => 
```

**Comment by lzap** [comment]
Thanks a bunch.

https://ci.theforeman.org/job/foreman-discovery-image-release/22/

http://downloads.theforeman.org/discovery/releases/3.7/

Have fun.

**Comment by petski** [comment]
Thanks @lzap, you were fast.

To answer your question regarding "why I need it": I actually use foreman-discovery-image (fdi) as a quality tool. We pick up the facts collected by fdi in a hook in foreman (i.e. via `./foreman/config/hooks/host/discovered/after_update/after_update.pl`) where we "judge" the facts and their values to see if they match with what we'd expect them to be.

**Comment by lzap** [comment]
Make sure to update to 3.7.3. I have just found a breaking issue in PXE-less workflow, releasing soon.

**Pull request merged**
