### PR TITLE
Remaster script works on old images as well

### PR DESCRIPTION
**Pull request by lzap**
For those who want to experiment with remastered 2.X images. Please note after
the host REBOOTs it wont be able to boot the installer. Old images do not
support kexecing yet. Also adds overwrite option for dev purposes.

### CODE REVIEW

**Comment by lzap** [comment]
And this one @stbenjam is nice to have (since I remaster quite often the new option is *very* handy). Thanks!

**Comment by stbenjam** [comment]
How does this work? The published 2.0 images aren't ISO's, right? Was just trying to test it out.

**Comment by lzap** [comment]
> How does this work? The published 2.0 images aren't ISO's, right? Was just trying to test it out.

Yes, a colleague of us asked me if he can remaster an old build, so I
made a changes. It will boot and register, but kexecing won't work and
since there is no TUI, it's very limited use.

This patch also adds useful extra cmd option :-)

-- 
Later,
 Lukas #lzap Zapletal

**Comment by stbenjam** [comment]
But how do I build an ISO for 2.0? It generates a tar and an img.

**Comment by lzap** [comment]
> But how do I build an ISO for 2.0? It generates a tar and an img.

Yeah, you can either extract the ISO from downstream RPM, or modify the
build script not to delete the resulting ISO file after initrd
extraction.

You don't need to test this, if it works for you with the current image
it's fine to merge this "as is".

-- 
Later,
 Lukas #lzap Zapletal

**Comment by stbenjam** [comment]
I just prefer to test the ones I can, anyway merged as d7792746ff0b9f8d17c89f6e6fe392973955405e, thanks

**Pull request closed without merging**
