### PR TITLE
Fixes #36757 - fix vlan id new line handling in nm-configure

### PR DESCRIPTION
**Pull request by amasolov**

### CODE REVIEW

**Comment by amasolov** [comment]
@evgeni I would appreciate if you can review this one.

**Comment by evgeni** [comment]
I have not the slightest idea about NM or FDI…

**Comment by nixfu** [comment]
I would really appreciate if this could be included and a new discovery iso published with this fix soon.  This is a major breaker for those using vlan networks and trying to use foreman-discovery.

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

**Comment by stejskalleos** [comment]
Thanks @amasolov , sorry it took so long.

**Pull request merged**
