### PR TITLE
small typo on fact auto_negotiation

### PR DESCRIPTION
**Pull request by elmer**
auto_negotitation => auto_negotiation typo

### CODE REVIEW

**Comment by lzap** [comment]
Thanks, @mhulan can you confirm that this won't introduce regression in RHOSP?

**Comment by ares** [comment]
Last time I saw the code, this fact was not used for anything. I doubt that the situation changed but if you want to be 100% sure, ask someone from the team...

**Comment by lzap** [comment]
Ok thank you:

13:43    @mburns | lzap: you can proceed with it

Thanks @elmer !

**Comment by lzap** [comment]
Merged as 3d4f477

**Pull request closed without merging**
