### PR TITLE
Fixes #19984 - added fdi.countdown to unattended pxeless

### PR DESCRIPTION
**Pull request by lzap**
Slow networks workaround.

### CODE REVIEW

**Comment by dLobatog** [comment]
Thanks, out of curiosity when did you need this?

**Comment by timogoebel** [comment]
@lzap: Is this related to https://github.com/theforeman/foreman-discovery-image/pull/90?

**Comment by lzap** [comment]
Sorta, this is the same thing but when you are using PXE less unattended mode (you put fdi.auto=1 onto cmdline).

**Comment by lzap** [comment]
So this was suggested by our customer, you can only run into this on slow DHCP networks or when NM is slow with net init (drivers, hardware).

**Pull request merged**
