### PR TITLE
Fixes #15195 - new option fdi.dhcp_timeout for IPv4

### PR DESCRIPTION
**Pull request by lzap**
Update docs when this is merged.

### CODE REVIEW

**Comment by lzap** [comment]
Warning: This option was introduced in RHEL 7.3, it will have zero effect for images based off 7.2 (hopefully it won't fail).

**Comment by stbenjam** [comment]
:+1: Thanks @lzap!.  Please update the docs with the new setting

**Comment by lzap** [comment]
https://github.com/theforeman/theforeman.org/pull/662 TY

**Comment by timogoebel** [comment]
@lzap : This bug is really, really bugging me. Any chance we can build an image based off of CentOS 7.3. It has been released by now. What needs to be done?

**Comment by lzap** [comment]
Thanks for ping, I missed the announcement. I will release new version for 1.14.

**Comment by lzap** [comment]
Had some troubles with building the new image on Rackspace, but fixed it and building now: https://github.com/mitchellh/vagrant-rackspace/pull/153

**Comment by lzap** [comment]
It's here, need to test it and announce: http://downloads.theforeman.org/discovery/releases/3.3/

**Pull request merged**
