### PR TITLE
add packages needed by foreman_discovery_image_installer

### PR DESCRIPTION
**Pull request by Raboo**
add packages needed by [foreman_discovery_image_installer](https://github.com/deltaprojects/foreman_discovery_image_installer).
Partially solves http://projects.theforeman.org/issues/19423.

### CODE REVIEW

**Comment by lzap** [comment]
Hey! How youre' doin'! I could not find time to work on my prototype yet, but I will indeed test and merge this. I hope it won't make the image much bigger.

I'd bet that SSM is in RHEL7, that woudl be surprise for me if it is in EPEL. Maybe newer version, but there must be one. I will check tomorrow.

**Comment by lzap** [comment]
Is ssm this?

```
Name        : system-storage-manager
Arch        : noarch
Version     : 0.4
Release     : 7.el7
Size        : 114 k
Repo        : rhel-7-server-rpms/7Server/x86_64
Summary     : A single tool to manage your storage
URL         : http://storagemanager.sf.net
License     : GPLv2+
Description : System Storage Manager provides an easy to use command line interface to manage
            : your storage using various technologies like lvm, btrfs, encrypted volumes and
            : more.
```

That's in RHEL/CentOS.

**Comment by lzap** [comment]
Indeed, please add it.

**Comment by Raboo** [comment]
Hi, Lukas
I'm pretty stressed out with work stuff. Severely understaffed 😭. Otherwise it's fine.
How are things with you?
You are right, ssm is in the main repo. Have added it to the PR now.

**Comment by lzap** [comment]
Great, can you squash into one commit following our guidelines in naming conventions and creating issue for that associating it properly via "Fixes #1234 - bla bla". Then I will test and merge, thanks!

https://www.theforeman.org/contribute.html

**Comment by Raboo** [comment]
squashed

**Comment by lzap** [comment]
Building http://ci.theforeman.org/view/Packaging/job/packaging_discovery_image/121/

**Comment by lzap** [comment]
All green http://downloads.theforeman.org/discovery/scratch/lzap-86/

**Comment by lzap** [comment]
Acceptable increase (+4 MB total). Thanks!

**Comment by Raboo** [comment]
Nice, thanks.
Is this targeted for 3.4.1 or 3.5.0 release of the image?

**Comment by lzap** [comment]
I'd like to do 3.4.1 but let's see.

**Pull request merged**
