### PR TITLE
SRV record resolve https for port 8443 or 9090

### PR DESCRIPTION
**Pull request by aaronkrzywicki**

### CODE REVIEW

**Comment by lzap** [comment]
Hello and thank you for your contribution, however there is a bug in your code. This statement is always true:

```
>> a = 1
=> 1
>> puts "A" if a == 443 || 8443
A
```

The correct form is:

```
>> puts "A" if a == 443 || a == 8443
```

Can you also add 9090 number? This number is often used with Satellite 6 and it is HTTPS as well. Reword the commit message a bit (it's a bit long) and we are good to go!

**Comment by lzap** [comment]
Ideally you can do something like:

    if [443, 8443, 9090].include?(result.port)

**Comment by aaronkrzywicki** [comment]
Updated as requested. Built FDI with new code and confirmed working on 8443.

**Comment by lzap** [comment]
We are good to go, can you squash into one commit please? I can merge then.

**Comment by aaronkrzywicki** [comment]
Squashed.

**Comment by lzap** [comment]
Merged as e90092a09032f351714cb5efbfe7299cfdc6f34b, thank you!

**Pull request closed without merging**
