### PR TITLE
Fixes #16419 - search domains honored during SRV

### PR DESCRIPTION
**Pull request by lzap**
Workarounds: https://bugs.ruby-lang.org/issues/11152

The patch also adds 'fdi.srv.scheme' new option to set http or https scheme for
custom port.

### CODE REVIEW

**Comment by lzap** [comment]
I am building a scratch build with this change, please leave comments if you test this.

**Comment by lzap** [comment]
http://downloads.theforeman.org/discovery/lzap/scratch/

**Comment by lzap** [comment]
@stbenjam @orrabin @dLobatog if you have time next week to test this PR. it contains a small enhancement and fix for nightly which was broken due incorrect gettext initialization (missing locales)

**Comment by dLobatog** [comment]
Merged as 65f9d2c1d40f1dd0e9fcc239ed1461a1db6ff439, thanks @lzap!

**Comment by lzap** [comment]
Thanks very much, we now have a nightly build which is also smaller thanks to the previous patch that removed Mac bootloaders! Whooo.

http://downloads.theforeman.org/discovery/nightly/

Let's wait for CentOS 7.3 for the release.

**Pull request closed without merging**
