### PR TITLE
Improved discovery-debug script

### PR DESCRIPTION
**Pull request by lzap**
Introduced in https://github.com/theforeman/foreman-discovery-image/pull/46
sorry!

### CODE REVIEW

**Comment by stbenjam** [comment]
Didn't the old one include the package version as well, is there a reason we're not doing that anymore?

**Comment by lzap** [comment]
Sorry I am not following...

**Comment by lzap** [comment]
@stbenjam can you elaborate?

I also simplified the debug script in this patch, the `--tui` option was I think unnecessary (it's purpose was to remove some things when called from TUI). I also removed one extra button - Network. It's always been already included in System log. I am making some space for another buttons for the future.

**Comment by stbenjam** [comment]
PACKAGE-LIST is just the package names.

**Comment by lzap** [comment]
Oh yeah, well since this is read only image, versions are not relevant in this context - RPM database is deleted, no chance to upgrade a package.

**Comment by stbenjam** [comment]
Right, but I wanted to see the version of the smart-proxy RPM to make sure what nightly it had installed. I suppose I could've looked at the build-live-cd output but if we're including a package list, why not have the version?

**Comment by lzap** [comment]
> Right, but I wanted to see the version of the smart-proxy RPM to make sure what nightly it had installed. I suppose I could've looked at the build-live-cd output but if we're including a package list, why not have the version?

Sure, updated:

```
rpm -qa --queryformat '%{SIZE} %{NAME}%{VERSION}%{RELEASE}\n' | head -n5
432073 perl-Math-BigInt1.9997350.fc23
62711 lockdev1.0.40.20.20111007git.fc23
245772 mathjax-sansserif-fonts2.4.02.fc23
2295691 jomolhari-fonts0.00320.fc23
20911 python3-pwquality1.3.02.fc23
```

-- 
Later,
 Lukas #lzap Zapletal

**Comment by stbenjam** [comment]
Thanks!! Merged as ad8c2b7ed74a3f2b3b3c6cdd2951ab20ac6b12df

**Pull request closed without merging**
